### ISSUE TITLE
Install pipeline.yml refers to non-existent pivnet-cli resource

### ISSUE THREAD

**Issue by wrast** [pivotal-cf/pcf-pipelines#25]
Wrong `glob` reference being used in `install-pcf/vsphere/pipeline.yml`.

```
- name: upload-elastic-runtime-tile
  plan:
...
    - get: pivnet-cli
      params: {globs: ["*linux_amd64*"]}
```

Should be:

```
- name: upload-elastic-runtime-tile
  plan:
...
    - get: pivnet-cli
      params: {globs: ["*linux-amd64*"]}
```

Note the dash usage instead of underscore in `globs`.
