### ISSUE TITLE
create-offline-pinned-pipelines broken because of missing pivnet artifact "pcf-automation"

### ISSUE THREAD

**Issue by punkadiddle** [pivotal-cf/pcf-pipelines#289]
## Issue

[create-offline-pinned-pipelines/pipeline.yml](/pivotal-cf/pcf-pipelines/blob/master/create-offline-pinned-pipelines/pipeline.yml) references a pivnet artifact called "pcf-automation", supposedly containing a release of this git, which does not exist.

## Context

The task `pcf-pipelines-tarball` fails to download `pcf-automation` and thus fails the `create-offline-pinned-pipelines` pipeline. Latest version (73f782e49b13eb681820374e3166d52c4167f3c4).

### Expected result

All downloads should run smoothly.

### Current result

task `pcf-pipelines-tarball` defect

## Steps to Reproduce

Run `create-offline-pinned-pipelines`

## Possible Fix

Tried to yaml_patch using the following snippet to download from github instead. However, further testing showed it's not equivalent; removed logs related to the evalution to not clutter the issue.
```yaml
- op: replace
  path: /resources/name=pcf-pipelines-tarball
  value:
    name: pcf-pipelines-tarball
    type: github-release
    source:
      # https://api.github.com/repos/pivotal-cf/pcf-pipelines/releases
      owner: pivotal-cf
      repository: pcf-pipelines
      release: true
      pre_release: true
```

## Logs and Screenshots

Running with original pipeline trying to download from pivnet, `pcf-pipelines-tarball` CHECK says:
```
resource script '/opt/resource/check []' failed: exit status 1

stderr:
2018/02/17 12:06:38 Exiting with error: could not find product with 'id' or 'slug'=pcf-automation
```
