### ISSUE TITLE
create-offline-pinned-pipelines fails due to mixed api token requirements

### ISSUE THREAD

**Issue by punkadiddle** [pivotal-cf/pcf-pipelines#290]
## Issue

Running `create-offline-pinned-pipelines` the task `create-tarball` within `create-elastic-runtime-tarball` contains a script that uses pivnet-cli which requires a legacy API token. Some of the other tasks seems to require new-style tokens and do not work with legacy.

## Context

Broken product requires additional time and qualification to fix.

### Expected result

Smooth download.

### Current result

`create-offline-pinned-pipelines` defect

## Steps to Reproduce

Run `create-offline-pinned-pipelines`

## Possible Fix

Provide both old an new style API tokens (patch below). Fix pivnet cli.

yaml_patch
```yaml
- op: replace
  path: /jobs/name=create-elastic-runtime-tarball/plan/task=create-tarball/config/params/PIVNET_API_TOKEN
  value: {{pivnet_legacy_token}}
```

## Logs and Screenshots

`create-elastic-runtime-tarball`  /  `create-tarball` output

```
Downloading stemcell 3468.21
+ pivnet-cli login --api-token=<replaced my new-style token>
Failed to login
```
