### ISSUE TITLE
Necessary to download pivnet stemcells and restore them?

### ISSUE THREAD

**Issue by aegershman** [pivotal-cf/pcf-pipelines#357]
## Issue

When upgrading from opsmgr 2.2.4 to 2.2.6, I noticed a twofold problem:
1. the `download-stemcells` task does not account for xenial stemcells [because the product glob pattern in the task does not account for it](https://github.com/pivotal-cf/pcf-pipelines/blob/master/tasks/download-pivnet-stemcells/task.sh#L58)
2. Downloading and restoring the xenial stemcells wasn't necessary, as the stemcells were already present after `import-opsmgr-settings` ran and I logged into the opsmgr. This makes me wonder if it is necessary to download pivnet stemcells / restore them at all?

## Context

We do not use `pcf-pipelines` directly. However, we did take inspiration from [the upgrade-opsmgr](https://github.com/pivotal-cf/pcf-pipelines/blob/master/upgrade-ops-manager/aws/pipeline.yml#L119-L132) pipeline, which has code to download/restore stemcells. At this point, however, we aren't sure if we even need to do that step at all? 

Our upgrade-opsmgr pipeline job which imports the opsmgr settings after upgrading the opsmgr VM. The pipeline looks (roughly) like this:

```yml
- name: import-opsman-settings
  plan:
  - task: import-opsmgr-settings
    file: pipeline-source/tasks/import-opsmgr-settings/task.yml
  - task: download-stemcells # <--- fails here
    file: pipeline-source/tasks/download-pivnet-stemcells/task.yml
  - task: restore-stemcells
    file: pipeline-source/tasks/restore-stemcells/task.yml
```

## Steps to Reproduce

Run the `download-pivnet-stemcells` task using a `diagnostic-report`(I included ours) which contains a product relying on the xenial stemcells (e.g. event alerts 1.2.3 which uses xenial 97.15)

## Possible Fix

1. if the exporting/importing of opsmgr settings includes all the stemcells required for installed products, you can probably just remove the `download-pivnet-stemcells`/`restore-stemcells` tasks altogether
2. modify the `download-pivnet-stemcells` task to account for products which require xenial stemcells

## Logs and Screenshots

![screen shot 2018-09-11 at 10 52 46 am](https://user-images.githubusercontent.com/5619476/45373095-2d16a680-b5b4-11e8-90ad-81db375b3210.png)
[diagnostic-report.zip](https://github.com/pivotal-cf/pcf-pipelines/files/2371807/diagnostic-report.zip)

thanks for your time!
